import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

function generateRuntimeAsset() {
	const assetsDir = "./assets";
	const files = fs.readdirSync(assetsDir);
	const tarball = files.find(f => f.startsWith("gephi-lite-v") && f.endsWith(".tar.gz"));
	
	if (!tarball) {
		throw new Error("No gephi-lite-v*.tar.gz file found in assets/ directory!");
	}
	
	const match = tarball.match(/^gephi-lite-v([\d.]+)\.tar\.gz$/);
	if (!match) {
		throw new Error(`Invalid tarball filename format: ${tarball}. Expected gephi-lite-vX.Y.Z.tar.gz`);
	}
	
	const version = match[1];
	const fileContent = `// This file is auto-generated by esbuild.config.mjs at build time.
import gephiArchive from "../../assets/${tarball}";
export const RUNTIME_VERSION = "${version}";
export default gephiArchive;
`;
	
	const targetPath = "./src/utils/runtime-asset.ts";
	fs.writeFileSync(targetPath, fileContent);
	console.log(`Generated ${targetPath} with version ${version} from ${tarball}`);
}

generateRuntimeAsset();

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Build host.ts first to be embedded in main.ts
await esbuild.build({
	entryPoints: ["src/host.ts"],
	bundle: true,
	outfile: "src/host-compiled.txt",
	platform: "browser",
	format: "iife",
	minify: prod,
});

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".gz": "binary",
		".txt": "text",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
